language: go
branches:
  only:
  - master
go:
- 1.11.4
services:
- docker
before_install:
  - go get github.com/goreleaser/goreleaser
script:
- make test
- make _output/bin/kubectl-trace
- ./hack/ci-build-image.sh
- make integration
- make cross
after_success:
- ./hack/ci-release-image.sh
