language: go
branches:
  only:
  - master
go:
- 1.11.4
services:
- docker
before_install:
- curl -LO https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_amd64.deb && sudo dpkg -i goreleaser_amd64.deb 
script:
- make test
- make _output/bin/kubectl-trace
- ./hack/ci-build-image.sh
- make integration
- make cross
after_success:
- ./hack/ci-release-image.sh

deploy:
- provider: script
  skip_cleanup: true
  script: goreleaser
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
