language: go
branches:
  only:
  - master
go:
- 1.11.4
services:
- docker
script:
- make test
- make _output/bin/kubectl-trace
- ./hack/ci-build-image.sh
- make integration
after_success:
- ./hack/ci-release-image.sh
